### ISSUE TITLE
Use of sigmoid in DTCF module

### ISSUE THREAD

**Issue by DevKiHyun** [JUiscoming/Duality-Temporal-Channel-Frequency-Attention-Enhanced-Speaker-Representation-Learning#1]
https://github.com/JUiscoming/Duality-Temporal-Channel-Frequency-Attention-Enhanced-Speaker-Representation-Learning/blob/5fc9efe11d4f347dc60f96075cf5e5b960f58109/modules.py#LL58C14-L58C21

hi. I wonder that why you are not use sigmoid function in DTCF module. 
Following the paper, we should apply sigmoid function to each attention scores for calculating the attention weights
 (https://github.com/JUiscoming/Duality-Temporal-Channel-Frequency-Attention-Enhanced-Speaker-Representation-Learning/blob/5fc9efe11d4f347dc60f96075cf5e5b960f58109/modules.py#L74)

**Comment by JUiscoming** [comment]
Hi @DevKiHyun , You are right!
I omitted to put sigmoid function after attention module :)
thank you to find this problem!
